---
# cmake-format configuration
# https://cmake-format.readthedocs.io/

parse:
  additional_commands: {}

format:
  line_width: 100
  tab_size: 4
  use_tabchars: false
  line_ending: unix
  max_lines_hwrap: 2
  max_subgroups_hwrap: 2
  min_prefix_chars: 4
  max_prefix_chars: 10
  dangle_parens: true
  dangle_align: prefix
  keyword_case: upper
  command_case: canonical
  always_wrap:
    - target_sources
    - target_link_libraries
    - target_include_directories
    - qt_add_qml_module
    - qt_add_executable
    - qt_add_library

markup:
  enable_markup: true
  first_comment_is_literal: true
...
